Option <skip>true|false</skip>
snyk/snyk-maven-plugin pull request #81
Opened 2020-10-09 16:31 UTC by aoterolorenzo

- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk-maven-plugin/blob/master/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

Closes #79 

 #### What does this PR do?

 #### Where should the reviewer start?

 #### How should this be manually tested?

 #### Any background context you want to provide?

 #### What are the relevant tickets?

 #### Screenshots

 #### Additional questions

2020-10-09 16:35 UTC, recena commented on pom.xml
> +  <version>1.2.8-SNAPSHOT</version>
I think you should set `1.2.9-SNAPSHOT` version

2020-10-09 16:35 UTC, recena commented on pom.xml
> +
Unrelated change.

2020-10-09 16:36 UTC, recena commented on pom.xml
> +
Unrelated change.

2020-10-09 16:37 UTC, recena commented on pom.xml
> +            <version>1.6</version>
This is an unrelated change but it could be included since improves the readability and avoid problems.

2020-10-09 16:38 UTC, recena commented on src/main/java/io/snyk/maven/plugins/SnykMonitor.java
> +        if(skip) {
Please, use the same coding style convention: `if (skip) {`

2020-10-09 16:38 UTC, recena commented on src/main/java/io/snyk/maven/plugins/SnykTest.java
> +        if(skip) {
Ditto

2020-10-09 16:39 UTC, recena requested changes
I left some comments.

2020-10-13 11:07 UTC, aoterolorenzo commented
Already passing tests after setting up Api key and endpoint in local except the license-issue. Need of contribution agreement? No incoming sign request not instructions after bring PR from Draft to review.

Output:
`[INFO] --- maven-invoker-plugin:2.0.0:integration-test (integration-test) @ snyk-maven-plugin ---
[INFO] Building: private-repo-module/pom.xml
[INFO] run script verify.bsh
[INFO] ..SUCCESS (3.6 s)
[INFO] Building: license-issues-module/pom.xml
[INFO] run script verify.bsh
**[INFO] ..FAILED (2.2 s)
[INFO]   The post-build script did not succeed. Missing license issue (EPL-1.0) for junit:junit@4.12
[INFO] Building: single-module/pom.xml**
[INFO] run script verify.bsh
[INFO] ..SUCCESS (2.7 s)
[INFO] Building: remediation/pom.xml
[INFO] run script verify.bsh
[INFO] ..SUCCESS (2.3 s)
[INFO] Building: multi-module/pom.xml
[INFO] run script verify.bsh
[INFO] ..SUCCESS (3.5 s)
[INFO] 
[INFO] --- maven-invoker-plugin:2.0.0:verify (integration-test) @ snyk-maven-plugin ---
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 4, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  license-issues-module/pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.313 s
[INFO] Finished at: 2020-10-13T13:01:35+02:00
[INFO] ------------------------------------------------------------------------
`

2020-10-16 10:59 UTC, pavel-snyk commented
Hi @aoterolorenzo, 

can you explain/elaborate your use-case for this option?

If you want to control whether `snyk test/monitor` will be executed during maven build, I would recommend to use Maven build profiles (this is maven-way to enable/disable plugins during builds). Since our plugin execution is not hard-coded in default lifecycle, there is no need to add `skip` option (in compare to `skipTest` option by test plugin).

This is why I would like to know your use-case, perhaps I miss something.

Thanks,
Pavel

2020-10-16 11:02 UTC, pavel-snyk commented
about failing integration tests: we have a pre-defined configuration for IT-tests. Since envvars will not be exported by GH forks, your configuration is different.
We know it and working on a portable solution.

2020-10-19 08:28 UTC, aoterolorenzo commented
> Hi @aoterolorenzo,
> 
> can you explain/elaborate your use-case for this option?
> 
> If you want to control whether `snyk test/monitor` will be executed during maven build, I would recommend to use Maven build profiles (this is maven-way to enable/disable plugins during builds). Since our plugin execution is not hard-coded in default lifecycle, there is no need to add `skip` option (in compare to `skipTest` option by test plugin).
> 
> This is why I would like to know your use-case, perhaps I miss something.
> 
> Thanks,
> Pavel

Hi @pavel-snyk,

In general terms, having a skip functionality on the plugin, provides more flexibility when it comes to configure complex multimodule projects.

Certainly you could replicate this behavior with Profiles, but is not a good practice, given the fact that their use in cases related to properties are not recommended by Maven conventions http://maven.apache.org/guides/introduction/introduction-to-profiles.html#profile-pitfalls

Furthermore there’s some quality metric plugins that are currently implemented this feature, like Checkstyle or Sportbugs, which have their respective `skip` functionality. 

Thank you,
Alberto.

2020-10-19 11:02 UTC, recena commented
I totally agree with @aoterolorenzo. Many Maven Core Plugins provide this mechanism to disable its execution.

2020-10-23 13:28 UTC, aoterolorenzo commented
@pavel-snyk just checking in, any updates on this?

Thank you,
Alberto

2020-10-28 20:46 UTC, recena commented
@pavel-snyk Is there any chance to review this proposal?

2020-11-06 15:15 UTC, recena commented
Hello @pavel-snyk, Is there any way to move forward this proposal?

2020-11-15 13:56 UTC, pavel-snyk commented
👋 @aoterolorenzo and @recena 
We discussed this proposal internally. That why it took longer:
1) you cannot compare the plugin with maven core plugins, I mentioned it in my comment before. Maven core plugins have builtin lifecycle (defined in xml).
2) about your link and pitfalls for profiles: this is not what the article explains. It means if you have e.g. an appserver with local path, you cannot run a build without defined this path, so the maven build will be not portable.
3) but I see the following use-case: if you have a multi-module project and you defined a snyk execution in parent pom, then disable/enable in child poms. It's doable with profiles or `skip` in configuration. In my opinion profiles are more clean approach, but there are a lot of custom (enterprise specific) builds we want to support.

**Summary**:
- please add a documentation for the `skip` option in readme file: https://github.com/snyk/snyk-maven-plugin#configuration
- take a look for my comment about skip logging

Cheers,
Pavel

2020-11-16 09:16 UTC, recena commented
@pavel-snyk Thank you so much for your feedback.

> 1. you cannot compare the plugin with maven core plugins, I mentioned it in my comment before. Maven core plugins have builtin lifecycle (defined in xml).

it is not about plugin comparison but use standard behaviors and common configurations.

> 2. about your link and pitfalls for profiles: this is not what the article explains. It means if you have e.g. an appserver with local path, you cannot run a build without defined this path, so the maven build will be not portable.

I agree it is not 100% clear but in my opinion is not good option to use profiles to enable plugins like this. But yes, it is a personal preference.

> 3. but I see the following use-case: if you have a multi-module project and you defined a snyk execution in parent pom, then disable/enable in child poms. It's doable with profiles or `skip` in configuration. In my opinion profiles are more clean approach, but there are a lot of custom (enterprise specific) builds we want to support.

Exactly, this is one of the use cases.
 
> **Summary**:
> 
> * please add a documentation for the `skip` option in readme file: https://github.com/snyk/snyk-maven-plugin#configuration
> * take a look for my comment about skip logging

We don't see that comment.

Regards,

2020-11-16 10:44 UTC, pavel-snyk commented
> We don't see that comment.
fixed it :), GH requires click on comment button twice 🤦

2020-11-16 10:47 UTC, aoterolorenzo commented
> > We don't see that comment.
> > fixed it :), GH requires click on comment button twice 🤦

No problem :) Updated in bcea127 addressing your comments. Thanks!

2020-11-16 10:48 UTC, pavel-snyk approved these changes

2020-11-16 10:48 UTC, merged

2020-11-16 11:12 UTC, recena reviewed
IMHO we shoud use more specific log messages.